# [START functions_ci_cd_cloud_build]
steps:
# Install dependencies
- name: python
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]
# Run unit tests
- name: python
  entrypoint: python
  args: ["-m", "pytest"]
  env:
    - 'DEGIRO_USERNAME=${_DEGIRO_USERNAME}'
    - 'DEGIRO_PASSWORD=${_DEGIRO_PASSWORD}'
# Build and deploy
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - deploy
    - degiro-dca
    - --gen2
    - --region=europe-west3
    - --trigger-http
    - --runtime=python310
    - --entry-point=main
    - --timeout=540
    - --set-env-vars=DEGIRO_USERNAME=${_DEGIRO_USERNAME},DEGIRO_PASSWORD=${_DEGIRO_PASSWORD}